### ISSUE TITLE
Indigo: USBブート時のカーネルが古い？

### ISSUE THREAD

**Issue by 7675t** [tork-a/live-cd2#37]
手元の新しめのデスクトップPCでUbuntu14.04.5のブートUSBで立ち上げると、正常に立ち上がり、インストールも終了するのに対し、

このTORKのLiveUSBで立ち上げると、acpi=offにしたりしないとそもそもブートせず、さらにイーサネットが使えなかったりして状況が異なります。

双方のメモリの/casper/のカーネルを見ると、

Ubuntu14.04.5の場合、

```
$ file vmlinuz.efi 
vmlinuz.efi: Linux kernel x86 boot executable bzImage, version 4.4.0-31-generic (buildd@lgw01-43) #50~14.04.1-Ubuntu SMP Wed J, RO-rootFS, swap_dev 0x6, Normal VGA
```

TORKのLiiveUSB3.0.3だと、
```
$ file vmlinuz.efi 
vmlinuz.efi: Linux kernel x86 boot executable bzImage, version 3.13.0-24-generic (buildd@batsu) #47-Ubuntu SMP Fri May 2 23:30, RO-rootFS, swap_dev 0x5, Normal VGA
```
とだいぶ古いカーネルになっていて、これが原因だと推測します。

**Comment by k-okada** [comment]
ありがとうございます．
#38 でも似たような方向がありますが、LiveUSB 3.0.3 のkineticだとどのバージョンになるでしょうか？

あと、本筋でないですが私の手元でfileコマンドを実施すると以下のようになりますが、何が違うでしょうか？？？？
```
$ file vmlinuz.efi
vmlinuz.efi: x86 boot sector
```
fileのバージョン？
```
$ file -v
file-5.14
magic file from /etc/magic:/usr/share/misc/magic
```

**Comment by 7675t** [comment]
> ありがとうございます．
#38 でも似たような方向がありますが、LiveUSB 3.0.3 のkineticだとどのバージョンになるでしょうか？

自分が試しているのはすべてLiveUSB3.0.3の話です．USBメモリをUbuntu16.04のマシンに挿して，

LiveUSB3.0.3の場合
```
tajima@omega:/media/tajima/Ubuntu_ROS ja amd64$ cd casper/
tajima@omega:/media/tajima/Ubuntu_ROS ja amd64/casper$ ls
filesystem.manifest         filesystem.size      initrd.lz  vmlinuz
filesystem.manifest-remove  filesystem.squashfs  memtest    vmlinuz.efi
tajima@omega:/media/tajima/Ubuntu_ROS ja amd64/casper$ file vmlinuz.efi 
vmlinuz.efi: Linux kernel x86 boot executable bzImage, version 3.13.0-24-generic (buildd@batsu) #47-Ubuntu SMP Fri May 2 23:30, RO-rootFS, swap_dev 0x5, Normal VGA
```

Ubuntu 16.04.3の場合
```
tajima@omega:/media/tajima/Ubuntu 16.04.3 LTS amd64$ cd casper/
tajima@omega:/media/tajima/Ubuntu 16.04.3 LTS amd64/casper$ ls
filesystem.manifest         filesystem.squashfs      vmlinuz.efi
filesystem.manifest-remove  filesystem.squashfs.gpg
filesystem.size             initrd.lz
tajima@omega:/media/tajima/Ubuntu 16.04.3 LTS amd64/casper$ file vmlinuz.efi 
vmlinuz.efi: Linux kernel x86 boot executable bzImage, version 4.10.0-28-generic (buildd@lgw01-12) #32~16.04.2-Ubuntu SMP Thu , RO-rootFS, swap_dev 0x7, Normal VGA
```

ちなみにfileのバージョン
```
$ file -v
file-5.25
magic file from /etc/magic:/usr/share/misc/magic
```

**Comment by 7675t** [comment]
あ，しまった，Ubuntu16.04と比べてもしょうがないか．でも，Ubuntu14.04の結果は最初に書いたとおりです．

**Comment by k-okada** [comment]
あ、いや、3.0.3 呼んでいるものにはindigo(14.04)の3.0.3と kinetic (16.04)のそれと２つバージョンがあります．

https://github.com/tork-a/live-cd2/releases

--
◉ Kei Okada


2017-09-13 9:03 GMT+09:00 Ryosuke Tajima <notifications@github.com>:

**Comment by 7675t** [comment]
あー，すいません，そういう意味ですか．いままでの話はすべてIndigoの話です（Kineticは #38の方で）

kinetic-tork-20170811_030545-3_0_3.isoをマウントして調べると，
```
tajima@omega:/media/tajima/Ubuntu_ROS ja amd64/casper$ ls
filesystem.manifest         filesystem.size      initrd.lz  vmlinuz
filesystem.manifest-remove  filesystem.squashfs  memtest    vmlinuz.efi
tajima@omega:/media/tajima/Ubuntu_ROS ja amd64/casper$ file vmlinuz
vmlinuz: Linux kernel x86 boot executable bzImage, version 4.10.0-32-generic (buildd@lcy01-01) #36~16.04.1-Ubuntu SMP Wed , RO-rootFS, swap_dev 0x7, Normal VGA
```
ということでUbuntu16.04とほぼ同じのようです．

**Comment by k-okada** [comment]
ありがとうございます．
少しわかってきたかもしれないです．不思議なのは手元のPCでつくるとindigoが4.4になる．

メモ：

ubuntu 16.04.3 - Kenel 4.4 (https://wiki.ubuntu.com/XenialXerus/ReleaseNotes)　ただし isoのcasperは 4.10
ubuntu 14.04.5 - Kenel 4.4 (https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes) ただしisoのcasperは4.4

linux-image-generic-lts-trusty - Kenel 3.13 (https://packages.ubuntu.com/ja/trusty/linux-image-generic-lts-trusty)
linux-image-generic-lts-xenial - Kenel 4.4 (https://packages.ubuntu.com/ja/trusty/linux-image-generic-lts-xenial)

**Comment by 7675t** [comment]
ありがとうございます。
ということはCircleCIが走ってるAWS側の問題？ Kernel 3.13ってけっこう古いですよね．

**Comment by k-okada** [comment]
最初、ホストマシンのkernelが関係あるかな、とおもったんだけどkineticはできているからねぇ．
で、linux-iamge-genericが使われるのかと思ったら、今度はkineticは4.4.10だし．．．
となると #38 はkernel version とは関係ないことになるけど、再現できますでしょうか？

**Comment by 7675t** [comment]
インストール先のマシン依存なのではないかと思います．なんで #38 の止まる原因はちがうかもしれないので，分けて考えたほうがいいかも

こちらはこのまえ購入したデスクトップPCで，3.0.3(Indigo)はカーネルオプションにacpi=offを入れないと起動しませんでした．

3.0.3のKineticはまだ試してないので，あとで試してみますが，Ubuntu16.04はすんなり入ったので，カーネルバージョンが同じなら多分大丈夫じゃないかと予想．

ワークショップに来る人が新し目のPCになっていくと，LiveUSBのカーネルが古いとダメなこともあるかもな，と思いました．

**Comment by k-okada** [comment]
3.0.4 で新しいカーネルになったと思います．確認してみてください．

**Comment by 7675t** [comment]
ありがとうございます．カーネルが新しくなってるのを確認しました．
3.0.3ではacpi=offでないと起動しなかったマシンで，
3.0.4では何もせずに通常起動することを確認しました．
これで新しいマシンでもトラブルが減るのではと期待できます．
