### ISSUE TITLE
v3.0.3 kinetic boot error

### ISSUE THREAD

**Issue by Moirai** [tork-a/live-cd2#38]
https://github.com/tork-a/live-cd2/issues/37#issue-255482771
と関連があるかもしれませんが，

３本USBメモリを替えて焼いて１つも正常にブートしませんでした．
v3.0.0は立ち上がった．

**Comment by k-okada** [comment]
立ち上がりの順番ですが，
1. Persistent / .. / Install の選択画面が出る
2. ブートのテキスト文字が流れる
3. GUIが上がる
となっていると思いますが，どこまで行きますでしょうか？こちらで試したところ，
A. 3 まで上がってLogin画面になるがキーボードを受け付けない 
B. リブートしたら２の後で画面が黒くなったままになる
C. 一度persistent なしでboot したら立ちあがあった
D. 次からはpersistent で立ち上がる
となりました．確かにpersistentのときには前回の終了状態によっては少し変なことになるような気がすることがあります．．．．

**Comment by Moirai** [comment]
い．エラーが出て立ち上がらない（２本）
ろ．３まで行ってキーボードを受け付けないし，左のメニューが出ない

の２パターンだったと思います．
同じメディアを何度もは繰り返しませんでした．

**Comment by Moirai** [comment]
違うイメージの話をしているような気がしますが，
３本，焼き直して，各３回ずつブートし直しました．
この画面で始まって，一番上を選択
![img_20170916_052629](https://user-images.githubusercontent.com/3022691/30502147-009bb4ea-9aa0-11e7-95c2-b6976d4d35b8.jpg)

すべてで以下のメッセージが出た後に，左にメニューがでない，という現象になりました．
![img_20170912_154058](https://user-images.githubusercontent.com/3022691/30501925-302cbf52-9a9f-11e7-94d5-d9d0a090f97a.jpg)

**Comment by Moirai** [comment]
急いではいないですし、kineticを使えるのか試したかっただけなので、
ご報告をと思ったまででですのでこのissueは閉じます。

**Comment by k-okada** [comment]
お手数をおかけします

焼き直し、はisoを焼いていますでしょうか？
それともusbからddで吸い出したイメージでしょうか？
後者だと、全て同じ挙動と言うのはイメージがおかしくなっている
可能性がありそうかなと思いました。
前者だとisoが失敗していそうです。今度USBを渡してもらえると嬉しいです
例えば ctrl+alt+f1でログインできるか、パーミッションはなどを試してみたいです。

**Comment by Moirai** [comment]
ここのreleaseから落としてきたisoです．
* 再度ダウンロードして焼きましたが現象は同じです．v3.0.4も同じです．
* CUIにしてログインすると
~~~
Permission denied: '/home/tork/.config/catkin'
$ sudo chown -R tork .config
$ sudo chgrp -R docker .config
~~~
* 再度ログインするとエラーメッセージは出なくなる
* が，GUIに戻ってもメニューはでない．
* 変更は保持されないので再起動すると.config/catkinはroot rootに戻る

v3.0.3，v3.0.4共に同じです．

**Comment by k-okada** [comment]
変更が保持されないのはpersistentでisoが焼かれていないからでしょうか？
df とすると何がでますでしょうか？

--
◉ Kei Okada


2017年9月17日 1:37 y.suzuki <notifications@github.com>:

**Comment by Moirai** [comment]
はい．そうでした．わかりました．
persistentで焼いてないからです．
https://github.com/tork-a/live-cd2/issues/38#issuecomment-329893868
↑ここで，なぜpersistentの選択肢が出ないんだろうと思ってました．
失礼しました．
