### ISSUE TITLE
Docker Hubのtork/indigoで補間が効かない

### ISSUE THREAD

**Issue by 7675t** [tork-a/live-cd2#41]
docker pull tork/indigoした環境だと，gitなどのサブコマンドの補間が効かない．
```
$ sudo apt install bash-completion
```
とすると治るのですが，どのファイルを変更すればいいでしょうか．
なぜかLiveUSBで立ち上げた環境だと入っています．

**Comment by 534o** [comment]
https://github.com/tork-a/live-cd2/blob/master/indigo/Dockerfile#L73
です．

**Comment by 7675t** [comment]
たぶん，osrf/ros:indigo-desktop-fullのイメージが古いのが原因かも．このイメージにはそもそもbash-completionパッケージがpackage listに無い(apt updateすると出てくる)

**Comment by k-okada** [comment]
Closed via #42
